### ISSUE TITLE
jupyter notebooks don't run.

### ISSUE THREAD

**Issue by mjfwest** [pymola/pymola#25]
In the jupyter notebooks provided there is a line `import pymola.gen_sympy` that results in 
`ModuleNotFoundError: No module named 'pymola.gen_sympy'`

The only reference I can find in the code to gen_sympy is the following line:
`
import pymola.backends.sympy.generator as gen_sympy
`
Is it possible that the juptyter notebooks were written for an earlier version of pymola, and have not been updated?

**Comment by jgoppert** [comment]
Yes, will fix, needs to be updated to the new module names. We have already fixed this on a recent PR and should be resolved soon.
