### ISSUE TITLE
pymola org logo

### ISSUE THREAD

**Issue by vdwees** [pymola/pymola#34]
I was feeling creative and I started experimenting with logo designs. Here are two variations of my favourite idea:

More complicated:
![pymola_logo](https://user-images.githubusercontent.com/24944371/33506038-fb05865c-d6bb-11e7-928e-7d7a6c0b6931.png)

Simpler:
![pymola_logo_plain](https://user-images.githubusercontent.com/24944371/33506035-f7c9479e-d6bb-11e7-9e79-ff25b7d411cb.png)

Motifs are the red ball from the Modelica logo, "M"-shaped python, and the equals sign supporting the python. Colours are based on the python logo, but are open to changing. Any objections?

**Comment by jackvreeken** [comment]
The white-eyed snake looks friendlier to me. And overall the logo does not look too busy to me, so a 👍 from me.

**Comment by vdwees** [comment]
![pymola_logo_plain](https://user-images.githubusercontent.com/24944371/34891765-c9de68aa-f7a4-11e7-853f-8bab51c7037e.png)

**Comment by vdwees** [comment]
Here it is, a little cleaned up:
![pymola_logo](https://user-images.githubusercontent.com/24944371/34892690-3882f192-f7a8-11e7-9991-542b4147c3cf.png)
(actual file is on MR #43 )

**Comment by jackvreeken** [comment]
Added in bcd6944a2e17bb9060a881998158ed9cc7ba0b04, and moved to subfolder (like NumPy) in 578fb50471dc8c8202a23a19663b96f4abbe86ea.
