### ISSUE TITLE
Use individual array elements in CasADi backend, instead of storing as vector/matrix

### ISSUE THREAD

**Issue by jackvreeken** [pymola/pymola#40]
1. Vector/matrix expansion is far from ideal, duplicating code and possibly resulting in a performance hit.
2. Using matrices limits us to only storing 2D arrays, whereas Modelica support higher dimensions as well.

JModelica stores individual elements as well,e.g. turning a matrix `x` into `x[1,1]`, `x[1,2]`, etc. Is there any downside to us doing it this way as well?

**Comment by vdwees** [comment]
If we were to somehow use pymola without `expand_vectors` being true, then we may be able to benefit from the memory efficiencies of the vector representation. But for performance, I think individual elements will always be faster.

**Comment by jackvreeken** [comment]
The original goal as I understood it is to keep the generated MX graph of CasADi as close as possible to Modelica representation. This means that for loops stay as maps, etc. For speed, it's always possible to expand to SX at the end, which would make everything simple again (no functions, just unary and binary operations). Closing this for now, until a serious bottleneck pops up with the current approach.
