### ISSUE TITLE
extend the aliasing algorithm to eliminate equivalent states

### ISSUE THREAD

**Issue by vdwees** [pymola/pymola#42]
As long as we do not alias states to each other, it will be difficult to match the performance of jmodelica. I propose extending the alias elimination algorithm to detect and alias states and derivative states to each other. @jackvreeken: is there any reason why we should not do this?

**Comment by jackvreeken** [comment]
I'm slightly worried that RTC-Tools's `transcribe()` will not understand that correctly, but it should be easy enough to implement and test (I think).

Does doing so really result in a speedup though? I was thinking that typically (derivative) states are not aliases of one another, e.g. volumes. Or is that quite different for the hydraulic components you are working with?

**Comment by vdwees** [comment]
As long as we alias both the state and its derivative state, I think transcribe() will be fine. There is at least one equation per hydraulic branch that could be eliminated. We may have to go this route if we can't coax enough performance out of pymola elsewhere.

**Comment by jackvreeken** [comment]
Do you have any numbers for the number of (decision) variables, equations, and constraints of Pymola versus JModelica?

**Comment by vdwees** [comment]
Not really a huge performance improvement. Closing.
