### ISSUE TITLE
parser compilation slow

### ISSUE THREAD

**Issue by jgoppert** [pymola/pymola#8]
@jbaayen Any idea why this got so slow? The main difference I see is cython, which it is a huge improvement that they have cython support now. Just unfortunate that it takes a couple of minutes to build.

Another cool feature about the non-cython version is you can see how much of the grammar you actually are covering, but obviously we will want to use cython for production: https://coveralls.io/builds/5306447/source?filename=pymola%2Fgenerated%2FModelicaParser.py.

**Comment by jackvreeken** [comment]
Cython has been removed in c6ab50a635035ec112693732a6458537827221bd, which makes installation fast again (and parsing not significantly slower).
